spring.application.name=sprinvoice

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.username=sprinvoice
spring.datasource.password=sprinvoice

server.port=8083

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
